INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Maison','Maison','Home','jiā','jia','家',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Ecole','Ecole','School','xuéxiào','xuexiao','学校',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Restaurant','Restaurant','Restaurant','fànguǎn','fanguan','饭馆',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Magasin, boutique','Magasin, boutique','Shop, store','shāngdiàn','shangdian','商店',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Hopital','Hopital','Hospital','yīyuàn','yiyuan','医院',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Gare','Gare','Railway station','huǒchēzhàn','huochezhan','火车站',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Chine','Chine','China','Zhōngguó','Zhongguo','中国',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Pekin','Pekin','Beijing','Běijīng','Beijing','北京',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Sur, en-haut','Sur, en-haut','Over, upper','shàng','shang','上',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Sous, en-bas','Sous, en-bas','Under, lower','xià','xia','下',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Devant','Devant','In front','qiánmiàn','qianmian','前面',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Derriere','Derriere','Behind','hòumiàn','houmian','后面',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Dans','Dans','In','lǐ','li','里',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Aujourd''hui','Aujourd''hui','','jīntiān','jintian','今天',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Demain','Demain','Tomorrow','míngtiān','mingtian','明天',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Hier','Hier','Yesterday','zuótiān','zuotian','昨天',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Matin','Matin','Morning','shàngwǔ','shangwu','上午',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Midi','Midi','Noon','zhōngwǔ','zhongwu','中午',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Apres-midi','Apres-midi','Afternoon','xiàwǔ','xiawu','下午',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Annee','Annee','Year','nián','nian','年',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Lune, mois','Lune, mois','Moon, month','yuè','yue','月',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Soleil, jour','Soleil, jour','Sun, day','rì','ri','日',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Semaine','Semaine','Week','xīngqī','xingqi','星期',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Goutte','Goutte','Drop','diǎn','dian','点',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Minute','Minute','Minute','fēnzhōng','fenzhong','分钟',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Maintenent','Maintenent','Now','xiànzài','xianzai','现在',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Duree','Duree','How long','shíhou','shihou','时候',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Pere','Pere','Father','bàba','baba','爸爸',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Mere','Mere','Mother','māma','mama','妈妈',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Fils','Fils','Son','érzi','erzi','儿子',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Fille','Fille','Daughter','nǚ''ér','nv''er','女儿',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Professeur','Professeur','Teacher','lǎoshī','laoshi','老师',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Etudiant','Etudiant','Student','xuésheng','xuesheng','学生',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Collegue d''ecole','Collegue d''ecole','Classmate','tóngxué','tongxue','同学',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Ami','Ami','Friend','péngyou','pengyou','朋友',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Docteur','Docteur','Doctor','yīshēng','yisheng','医生',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Monsieur','Monsieur','Mister','xiānsheng','xiansheng','先生',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Mademoiselle','Mademoiselle','Miss','xiǎojiě','xiaojie','小姐',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Vetements','Vetements','Clothes','yīfu','yifu','衣朊',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Eau','Eau','Water','shuǐ','shui','水',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Plat','Plat','Dish','cài','cai','菜',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Riz','Riz','Rice','mǐfàn','mifan','米饭',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Fruit','Fruit','Fruit','shuǐguǒ','shuiguo','水果',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Pomme','Pomme','Apple','píngguǒ','pingguo','苹果',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('The','The','Tea','chá','cha','茶',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Tasse','Tasse','Mug','bēizi','beizi','杯子',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Argent','Argent','Cash','qián','qian','钱',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Avion','Avion','Airplane','fēijī','feiji','飞机',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Taxi','Taxi','Cab','chūzūchē','chuzuche','出租车',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Television','Television','Television','diànshì','dianshi','电视',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Ordinateur','Ordinateur','Computer','diànnǎo','diannao','电脑',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Film','Film','Movie','diànyǐng','dianying','电影',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Meteo, temps','Meteo, temps','Weather','tiānqì','tianqi','天气',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Chat','Chat','Cat','māo','mao','猫',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Chien','Chien','Dog','gǒu','gou','狗',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Quelque chose','Quelque chose','Something','dōngxi','dongxi','东西',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Personne','Personne','Person','rén','ren','人',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Nom','Nom','Name','míngzi','mingzi','吊字',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Livre','Livre','Book','shū','shu','书',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Chinois','Chinois','Chinese','Hànyǔ','Hanyu','汉语',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Caractere','Caractere','Character','zì','zi','字',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Table','Table','Table','zhuōzi','zhuozi','桌子',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Chaise','Chaise','Chair','yǐzi','yizi','椅子',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Merci','Merci','Thank you','xièxie','xiexie','谢谢',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('???','???','???','bú','bu','上',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Politesse','Politesse','Politeness','kèqi','keqi','客气',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Bye','Bye','Goodbye','zàijiàn','zaijian','再见',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Inviter, demander','Inviter, demander','Invite, Ask','qǐng','qing','请',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Desole','Desole','Sorry','duìbuqǐ','duibuqi','对上起',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Rien','Rien','None','méi','mei','没',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Relation','Relation','Relation','guānxi','guanxi','关系',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Etre','Etre','To be','shì','shi','是',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Avoir','Avoir','Have','yǒu','you','有',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Voir, Lire','Voir, Lire','See, read','kàn','kan','看',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Ecouter','Ecouter','Listen','tīng','ting','听',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Parler','Parler','Speak','shuōhuà','shuohua','说话',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Lire (a voix haute)','Lire (a voix haute)','Read (aloud)','dú','du','读',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Ecrire','Ecrire','Write','xiě','xie','写',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Appercevoir','Appercevoir','See','kànjiàn','kanjian','看见',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Nommer','Nommer','Give name','jiào','jiao','叫',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Venir','Venir','Come (to)','lái','lai','来',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Retourner','Retourner','Go back, return','huí','hui','回',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Aller','Aller','Go','qù','qu','去',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Manger','Manger','Eat','chī','chi','吃',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Boire','Boire','Drink (to)','hē','he','喝',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Dormir','Dormir','Sleep (to)','shuìjiào','shuijiao','睡觉',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Frapper','Frapper','Hit (to)','dǎ','da','打',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Telephone','Telephone','Phone','diànhuà','dianhua','电话',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Faire','Faire','Do (make)','zuò','zuo','做',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Acheter','Acheter','Buy','mǎi','mai','买',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Ouvrir','Ouvrir','Open','kāi','kai','开',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Assoir','Assoir','Sit','zuò','zuo','坐',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Habiter','Habiter','Live (in house)','zhù','zhu','住',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Etudier','Etudier','Study','xuéxí','xuexi','学习',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Travail','Travail','Work','gōngzuò','gongzuo','工作',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('En-bas','En-bas','Down, under','xià','xia','下',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Pluie','Pluie','Rain','yǔ','yu','雨',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Aimer','Aimer','Love','ài','ai','爱',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Aimer','Aimer','To like','xǐhuan','xihuan','喜欢',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Pense, Aimerais','Pense, Aimerais','Think, would like','xiǎng','xiang','想',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Connaitre','Connaitre','To know','rènshi','renshi','认识',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Devrais','Devrais','Shall','huì','hui','会',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Capable','Capable','Able','néng','neng','能',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Bon','Bon','Good','hǎo','hao','好',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Gros','Gros','Big','dà','da','大',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Petit','Petit','Small','xiǎo','xiao','小',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Plusieurs','Plusieurs','Many','duō','duo','多',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Moins','Moins','Less (few)','shǎo','shao','少',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Froid','Froid','Cold','lěng','leng','冷',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Chaud','Chaud','Hot','rè','re','热',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Heureux','Heureux','Happy','gāoxìng','gaoxing','高兴',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Beau','Beau','handsome','piàoliang','piaoliang','漂亮',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Je','Je','I','wǒ','wo','我',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Tu','Tu','You','nǐ','ni','你',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Il','Il','He','tā','ta','他',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Elle','Elle','She','tā','ta','她',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Nous','Nous','We','wǒmen','women','我们',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Ici','Ici','Here?Now?Then','zhè','zhe','这',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Ici','Ici','Here?Now?Then','zhèr','zher','这儿',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('La','La','There','nà','na','那',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('La','La','There','nàr','nar','那儿',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Ou','Ou','Where','nǎ','na','哪',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Ou','Ou','Where','nǎr','nar','哪儿',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Qui','Qui','Who','shéi','shei','谁',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Quoi','Quoi','What','shénme','shenme','什么',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Combien','Combien','How much','duōshao','duoshao','多少',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Plusieurs','Plusieurs','Several','jǐ','ji','几',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Pourquoi','Pourquoi','Why','zěnme','zenme','怎么',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Comment','Comment','How (about)','zěnmeyàng','zenmeyang','怎么样',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Un','Un','One','yī','yi','一',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Deux','Deux','Two','èr','er','二',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Trois','Trois','Three','sān','san','三',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Quatre','Quatre','Four','sì','si','四',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Cinq','Cinq','Five','wǔ','wu','五',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Six','Six','Six','liù','liu','六',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Sept','Sept','Seven','qī','qi','七',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Huit','Huit','Eight','bā','ba','八',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Neuf','Neuf','Nine','jiǔ','jiu','九',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Dix','Dix','Ten','shí','shi','十',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Zero','Zero','Zero','líng','ling','零',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Unite','Unite','Unit','gè','ge','个',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Annee','Annee','Year (old)','suì','sui','岁',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('???','???','???','běn','ben','本',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Quelques','Quelques','Some','xiē','xie','些',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Piece','Piece','Piece','kuài','kuai','块',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('???','???','???','bù','bu','上',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Sans, aucun','Sans, aucun','None','méi','mei','没',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Tres','Tres','Very','hěn','hen','很',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Trop','Trop','Too','tài','tai','太',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Tout','Tout','All','dōu','dou','都',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Et','Et','And','hé','he','和',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('','','at','zài','zai','在',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Appartenance','Appartenance','ownership','de','de','的',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Passe','Passe','past','le','le','了',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Est-ce que','Est-ce que','?','ma','ma','吗',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('???','???','How about','ne','ne','呢',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Allo','Allo','Hello','wèi','wei','喂',1,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Tante','Tante','Aunt','āyí','ayi','阿姨',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Ah!','Ah!','Ah!','a','a','啊',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Court, bas','Court, bas','Short, low','ǎi','ai','矮',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Preference','Preference','Prefer, like','àihào','aihao','爱好',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Calme','Calme','Calm, quiet','ānjìng','anjing','安静',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Poignee','Poignee','Handle','bǎ','ba','把',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Probablement','Probablement','Probably','ba','ba','吧',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Blanc','Blanc','White','bái','bai','白',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Cent','Cent','Hundred','bǎi','bai','百',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Equipe','Equipe','Team','bān','ban','班',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Deplacer','Deplacer','Move','bān','ban','搬',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Moitie','Moitie','Half','bàn','ban','半',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Facon, methode','Facon, methode','Way, method','bànfǎ','banfa','办法',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Bureau','Bureau','Office','bàngōngshì','bangongshi','办公室',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Aider?','Aider?','Help?','bāngmáng','bangmang','帮忙',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Aider','Aider','Help','bāngzhù','bangzhu','帮助',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Emballer','Emballer','To pack','bāo','bao','包',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('???','???','???','bǎo','bao','饱',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Journal','Journal','Newspaper','bàozhǐ','baozhi','报纸',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Nord','Nord','North','běifāng','beifang','北方',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('???','???','???','bèi','bei','被',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Nez','Nez','Nose','bízi','bizi','鼻子',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Que','Que','Than','bǐ','bi','比',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Compare a','Compare a','Compared to','bǐjiào','bijiao','比较',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Course','Course','Race','bǐsài','bisai','比赛',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Doit','Doit','Must','bìxū','bixu','必须',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Changement','Changement','A change','biànhuà','bianhua','变化',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Montrer, exprimer','Montrer, exprimer','Show, to express','biǎoshì','biaoshi','表示',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Jouer, acter','Jouer, acter','To play, acting','biǎoyǎn','biaoyan','表演',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Quitter','Quitter','To leave','bié','bie','别',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Autres (gens)','Autres (gens)','Other (people)','biéren','bieren','别人',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Hotel, maison invites','Hotel, maison invites','Inn, guesthouse','bīnguǎn','binguan','宾馆',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Frigo','Frigo','Fridge','bīngxiāng','bingxiang','冰箱',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Talent','Talent','Talent','cái','cai','才',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Menu','Menu','Menu','càidān','caidan','菜单',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Assister a','Assister a','To attend','cānjiā','canjia','参加',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Herbe','Herbe','Grass','cǎo','cao','草',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Couche, etage','Couche, etage','Layer, floor','céng','ceng','层',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Difference','Difference','Difference','chà','cha','差',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Long, Longueur','Long, Longueur','Long, length','cháng','chang','长',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Chanter','Chanter','To sing','chànggē','changge','唱歌',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Supermarche','Supermarche','Supermarket','chāoshì','chaoshi','超市',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Chemise','Chemise','Shirt','chènshān','chenshan','衬衫',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Resultat, pointage','Resultat, pointage','Result, score','chéngjì','chengji','成绩',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Ville','Ville','City','chéngshì','chengshi','城市',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('En retard','En retard','Late (to be)','chídào','chidao','迟到',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Sortir','Sortir','To go out','chū','chu','出',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Apparaitre','Apparaitre','To appear','chūxiàn','chuxian','出现',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Cuisine','Cuisine','Kitchen','chúfáng','chufang','厨房',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Sauf','Sauf','Except','chúle','chule','除了',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Transpercer','Transpercer','Pierce through','chuān','chuan','穿',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Navire, bateau','Navire, bateau','Ship','chuán','chuan','船',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Printemps','Printemps','Spring','chūn','chun','春',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Expression','Expression','Expression','cíyǔ','ciyu','词语',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Ordre, sequence','Ordre, sequence','Order, sequence','cì','ci','次',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Sage, intelligent','Sage, intelligent','Wise, intelligent','cōngming','congming','聪明',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('De, depuis','De, depuis','From, since','cóng','cong','从',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Faute','Faute','Fault, mistake','cuò','cuo','错',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Jouer au basketball','Jouer au basketball','Play basketball','dǎlánqiú','dalanqiu','打篮球',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Nettoyer','Nettoyer','To clean','dǎsǎo','dasao','打扫',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Planifier, avoir l''intention','Planifier, avoir l''intention','To plan, to intend','dǎsuàn','dasuan','打算',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Tous','Tous','Everybody','dàjiā','dajia','大家',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Bande','Bande','Strip','dài','dai','带',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('S''inquieter','S''inquieter','To worry','dānxīn','danxin','担心',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Gateau','Gateau','Cake','dàngāo','dangao','蛋糕',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Mais','Mais','But','dànshì','danshi','但是',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Certainement','Certainement','Certainly','dāngrán','dangran','当然',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('???','???','???','dào','dao','到',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('???','???','???','de','de','地',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('???','???','???','de','de','得',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Lampe','Lampe','Lamp','dēng','deng','灯',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('???','???','???','děng','deng','等',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Bas','Bas','Low','dī','di','低',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Jeune frere','Jeune frere','Young brother','dìdi','didi','弟弟',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Endroit?','Endroit?','Place?','dìfang','difang','地方',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Metro','Metro','Subway','dìtiě','ditie','地铁',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Carte','Carte','Map','dìtú','ditu','地图',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Debut','Debut','Start','dì-yī','di-yi','第一',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Ascenseur','Ascenseur','Elevator','diàntī','dianti','电梯',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Courriel','Courriel','email','diànzǐyóujiàn','dianziyoujian','电子邮件',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Est','Est','East','dōng','dong','东',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Hiver','Hiver','Winter','dōng','dong','冬',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Comprendre','Comprendre','Understand','dǒng','dong','懂',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Animal','Animal','Animal','dòngwù','dongwu','动物',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Court','Court','Short','duǎn','duan','短',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('???','???','???','duàn','duan','段',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('S''entrainer','S''entrainer','To train','duànliàn','duanlian','锻炼',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Correct','Correct','Correct','duì','dui','对',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('???','???','???','duōme','duome','多么',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Avoir faim','Avoir faim','Hungry','è','e','饿',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Et, aussi','Et, aussi','And, as well','érqiě','erqie','而且',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Oreille','Oreille','Ear','ěrduo','erduo','耳朵',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Avoir la fievre','Avoir la fievre','To have a fever','fāshāo','fashao','发烧',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Trouver, decouvrir','Trouver, decouvrir','Find, discover','fāxiàn','faxian','发现',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Accomodation','Accomodation','Conveniance','fāngbiàn','fangbian','方便',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Piece','Piece','Room','fángjiān','fangjian','房间',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Mettre, assigner?','Mettre, assigner?','Put, assign','fàng','fang','放',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Reassurer','Reassurer','Reassure','fàngxīn','fangxin','放心',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Beaucoup, tres','Beaucoup, tres','Much, very','fēicháng','feichang','非常',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Partie','Partie','Part','fēn','fen','分',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Serveur','Serveur','Waiter','fúwùyuán','fuwuyuan','服务员',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Voisinage','Voisinage','Neighbouring','fùjìn','fujin','附近',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Reviser','Reviser','Review','fùxí','fuxi','复习',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Propre','Propre','Clean','gānjìng','ganjing','干净',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Oser','Oser','Dare','gǎn','gan','敢',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Avoir un rhume','Avoir un rhume','To catch a cold','gǎnmào','ganmao','感冒',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Il y a peu de temps','Il y a peu de temps','A short while ago','gāngcái','gangcai','刚才',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Grand, haut','Grand, haut','Tall high','gāo','gao','高',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Dire, informer','Dire, informer','Tell, inform','gàosu','gaosu','告诉',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Frere aine','Frere aine','Older brother','gēge','gege','哥哥',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Donner, fournir','Donner, fournir','Give, provide','gěi','gei','给',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Talon','Talon','Heel','gēn','gen','跟',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Une base, cause','Une base, cause','A basis, cause','gēnjù','genju','根据',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('???','???','???','gèng','geng','更',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Autobus public','Autobus public','Public bus','gōnggòngqìchē','gonggongqiche','公共汽车',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Kilogramme','Kilogramme','Kilogram','gōngjīn','gongjin','公斤',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Compagnie','Compagnie','Company','gōngsī','gongsi','公司',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Parc','Parc','Park','gōngyuán','gongyuan','公园',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Histoire','Histoire','Story','gùshi','gushi','故事',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Souffler','Souffler','To blow','guāfēng','guafeng','刮风',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Fermer','Fermer','Close','guān','guan','关',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Relation','Relation','Relation','guānxì','guanxi','关系',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Se soucier','Se soucier','Care, concern','guānxīn','guanxin','关心',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('A propos, referer a','A propos, referer a','About, refer to','guānyú','guanyu','关于',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Dispendieux','Dispendieux','Expensive','guì','gui','贵',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Pays','Pays','Country','guójiā','guojia','国家',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Jus (de fruit)','Jus (de fruit)','Juice (fruit)','guǒzhī','guozhi','果汁',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Passe','Passe','Past','guòqù','guoqu','过去',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Traverser, passer','Traverser, passer','Cross, pass','guo','guo','过',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('???','???','???','hái','hai','还',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Ou','Ou','Or','háishì','haishi','还是',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Enfant','Enfant','Child','háizi','haizi','孩子',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Craindre, avoir peur','Craindre, avoir peur','To fear, to be scared of','hàipà','haipa','害怕',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Delicieux','Delicieux','Delicious','hǎochī','haochi','好吃',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('???','???','???','hào','hao','号',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Riviere','Riviere','River','hé','he','河',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Noir','Noir','Black','hēi','hei','黑',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Tableau','Tableau','Blackboard','hēibǎn','heiban','黑板',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Rouge','Rouge','Red','hóng','hong','红',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Passeport','Passeport','Passport','hùzhào','huzhao','护照',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Fleur','Fleur','Flower','huā','hua','花（动）',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Jardin (fleur)','Jardin (fleur)','Garden (flower)','huāyuán','huayuan','花园',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Dessiner','Dessiner','To draw (a picture)','huà','hua','画',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('???','???','???','huài','huai','坏',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Bienvenu','Bienvenu','Welcome','huānyíng','huanying','欢迎',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Revenir?','Revenir?','To return somewhere','huán','huan','还',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Environnement','Environnement','Environment, ambiance?','huánjìng','huanjing','环境',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Echanger','Echanger','Exchange','huàn','huan','换',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Jaune','Jaune','Yellow','huáng','huang','黄',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Repondre','Repondre','To answer','huídá','huida','回答',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Rencontre, conference','Rencontre, conference','Meeting, conference','huìyì','huiyi','会议',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Peut-etre','Peut-etre','Maybe','huòzhě','huozhe','或者',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Aeroport','Aeroport','Airport','jīchǎng','jichang','机场',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Oeuf','Oeuf','Egg','jīdàn','jidan','鸡蛋',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Presque','Presque','Almost','jīhū','jihu','几乎',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Opportunite','Opportunite','Opportunity','jīhuì','jihui','机会',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Extreme?','Extreme?','Extreme?','jí','ji','极',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Se souvenir','Se souvenir','Remember','jìde','jide','记得',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Saison','Saison','Season','jìjié','jijie','季节',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Examiner','Examiner','Examine','jiǎnchá','jiancha','检查',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Simplicite','Simplicite','Simplicity','jiǎndān','jiandan','简单',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Unite items','Unite items','Unit for items','jiàn','jian','件',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Sain','Sain','Healthy','jiànkāng','jiankang','健康',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Rencontrer (en personne)','Rencontrer (en personne)','Meet (in person)','jiànmiàn','jianmian','见面',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Dire, parler de','Dire, parler de','Say, talk about','jiǎng','jiang','讲',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Enseigner','Enseigner','Teach','jiāo','jiao','教',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Angle?','Angle?','Angle?','jiǎo','jiao','角',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Pieds','Pieds','Feet (body)','jiǎo','jiao','脚',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Salle de classe','Salle de classe','Classroom','jiàoshì','jiaoshi','教室',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('???','???','???','jiē','jie','接',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Rue','Rue','Street','jiēdào','jiedao','街道',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Se marier','Se marier','Marry','jiéhūn','jiehun','结婚',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('???','???','???','jiéshù','jieshu','结束',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Spectacle','Spectacle','Program, show','jiémù','jiemu','节目',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Fete, festival','Fete, festival','Festival','jiérì','jieri','节日',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Soeur ainee','Soeur ainee','Elder sister','jiějie','jiejie','姐姐',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Resoudre','Resoudre','Resolve','jiějué','jiejue','解决',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Emprunter','Emprunter','To borrow','jiè','jie','借',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Presenter','Presenter','Introduce','jièshào','jieshao','介绍',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('???','???','???','jìn','jin','进',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Proche','Proche','Near','jìn','jin','近',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Regulierement','Regulierement','Regularly','jīngcháng','jingchang','经常',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Passer','Passer','Go by','jīngguò','jingguo','经过',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Gerant','Gerant','Manager','jīnglǐ','jingli','经理',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Longtemps','Longtemps','For a long time','jiǔ','jiu','久',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Vieux','Vieux','Old','jiù','jiu','旧',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('A proximite','A proximite','Near by','jiù','jiu','就',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Tenir (une conference)','Tenir (une conference)','Hold (a conference)','jǔxíng','juxing','举行',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Phrase','Phrase','Sentence','jùzi','juzi','句子',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Sentir','Sentir','Feel','juéde','juede','觉得',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Decider','Decider','Decide','juédìng','jueding','决定',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Cafe','Cafe','Coffee','kāfēi','kafei','咖啡',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Commencer','Commencer','To begin','kāishǐ','kaishi','开始',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Examen','Examen','Exam','kǎoshì','kaoshi','考试',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Soif','Soif','Thirst','kě','ke','渴',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Beaute','Beaute','Loveliness','kěài','keai','可爱',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Peut','Peut','May','kěnéng','keneng','可能',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Pourrait','Pourrait','Could','kěyǐ','keyi','可以',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('???','???','???','kè','ke','刻',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Un cours','Un cours','A course','kè','ke','课',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Invite','Invite','Guest','kèrén','keren','客人',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Air climatise','Air climatise','Air conditionner','kōngtiáo','kongtiao','空调',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Bouche','Bouche','Mouth','kǒu','kou','口',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Pleurer','Pleurer','Cry','kū','ku','哭',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Pantalons','Pantalons','Pants','kùzi','kuzi','裤子',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Vite','Vite','Quick','kuài','kuai','快',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Joyeux','Joyeux','Happy','kuàilè','kuaile','快乐',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Baguettes','Baguettes','Chopsticks','kuàizi','kuaizi','筷子',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Bleu','Bleu','Blue','lán','lan','蓝',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Vieux','Vieux','Old','lǎo','lao','老',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Fatigue','Fatigue','Tired','lèi','lei','累',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Sortir, quitter','Sortir, quitter','Leave','lí','li','离',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Depart','Depart','Departure','líkāi','likai','离开',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Cadeau','Cadeau','Gift','lǐwù','liwu','礼物',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Histoire','Histoire','History','lìshǐ','lishi','历史',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Visage, face','Visage, face','Face','liǎn','lian','脸',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Exercice','Exercice','Exercise','liànxí','lianxi','练习',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Deux','Deux','Two','liǎng','liang','两',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Unite vehicule','Unite vehicule','Quantifier land vehicules','liàng','liang','辆',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Comprendre','Comprendre','Understand','liǎojiě','liaojie','了解',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Voisin','Voisin','Neighbor','línjū','linju','邻居',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Etage','Etage','Floor, story','lóu','lou','楼',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Route','Route','Road','lù','lu','路',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Voyage','Voyage','Trip, tour','lǚyóu','lvyou','旅游',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Vert','Vert','Green','lǜ','lv','绿',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Cheval','Cheval','Horse','mǎ','ma','马',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Immediatement','Immediatement','Immediately','mǎshàng','mashang','马上',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Vendre','Vendre','Sell','mài','mai','卖',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Satisfait','Satisfait','Satisfied','mǎnyì','manyi','满意',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Lent','Lent','Slow','màn','man','慢',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Occupe','Occupe','Busy','máng','mang','忙',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Chapeau','Chapeau','Hat','màozi','maozi','帽子',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Chaque','Chaque','Every','měi','mei','每',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Soeur cadette','Soeur cadette','Younger sister','mèimei','meimei','妹妹',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Porte, entree','Porte, entree','Door, entrance','mén','men','门',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Riz','Riz','Rice','mǐ','mi','米',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Pain','Pain','Bread','miànbāo','mianbao','面包',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Nouilles','Nouilles','Noodles','miàntiáo','miantiao','面条',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Clair, explicite, compris','Clair, explicite, compris','Clear, explicit, understood','míngbai','mingbai','明白',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Prendre','Prendre','Take','ná','na','拿',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Grand-mere','Grand-mere','Grandmother','nǎinai','nainai','奶奶',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Sud','Sud','South','nán','nan','南',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Homme','Homme','Man','nánrén','nanren','男人',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Difficile','Difficile','Difficult','nán','nan','难',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Malheureux','Malheureux','Unhappy','nánguò','nanguo','难过',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Annee, education, scolarisation','Annee, education, scolarisation','Year, grade','niánjí','nianji','年级',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Jeune','Jeune','Young','niánqīng','nianqing','年轻',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Oiseau','Oiseau','Bird','niǎo','niao','鸟',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Vous (politesse)','Vous (politesse)','You (polite)','nín','nin','您',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Lait','Lait','Milk','niúnǎi','niunai','牛奶',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('???','???','???','nǔlì','nuli','努力',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Femme','Femme','Women','nǚrén','nvren','女人',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Escalader une montagne','Escalader une montagne','Climb mountain','páshān','pashan','爬山',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Assiete','Assiete','Plate','pánzi','panzi','盘子',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('A cote','A cote','By the side of','pángbiān','pangbian','旁边',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Obese','Obese','Obese','pàng','pang','胖',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Courir','Courir','Run','pǎobù','paobu','跑步',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Biere','Biere','Beer','píjiǔ','pijiu','啤酒',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Avantageux, peu couteux','Avantageux, peu couteux','Advantageous, inexpensive','piányi','pianyi','便宜',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Billet','Billet','Ticket','piào','piao','票',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Raisin','Raisin','Grape','pútao','putao','葡萄',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Mandarin','Mandarin','Mandarin','pǔtōnghuà','putonghua','普通话',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Epouse, conjointe','Epouse, conjointe','Wife','qīzi','qizi','妻子',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('En fait','En fait','In fact','qíshí','qishi','其实',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Autre','Autre','Else','qítā','qita','其他',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Etre passager?','Etre passager?','To be a passenger, have a ride?','qí','qi','骑',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Etrange','Etrange','Strange','qíguài','qiguai','奇怪',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Se lever','Se lever','To get up','qǐchuáng','qichuang','起床',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Mille','Mille','Thousand','qiān','qian','千',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Crayon','Crayon','Pencil','qiānbǐ','qianbi','铅笔',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Clair, evident','Clair, evident','Clear, obvious','qīngchu','qingchu','清楚',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('???','???','???','qíng','qing','晴',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Automne','Automne','Fall, autumn','qiū','qiu','秋',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('L''an passee','L''an passee','Last year','qùnián','qunian','去年',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Jupe','Jupe','Skirt','qúnzi','qunzi','裙子',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Ensuite, suivant','Ensuite, suivant','Next','ránhòu','ranhou','然后',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Donner, permettre','Donner, permettre','Give, allow','ràng','rang','让',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Ardeur, devotion','Ardeur, devotion','Ardour, devotion','rèqíng','reqing','热情',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Juger, considerer','Juger, considerer','Judge, consider','rènwéi','renwei','认为',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Sincere','Sincere','Earnest','rènzhēn','renzhen','认真',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Facile','Facile','Easy','róngyì','rongyi','容易',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Si','Si','If','rúguǒ','ruguo','如果',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Parapluie','Parapluie','Umbrella','sǎn','san','伞',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Travail','Travail','Work','shàngbān','shangban','上班',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Aller sur internet','Aller sur internet','To go on internet','shàngwǎng','shangwang','上网',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Corps','Corps','Body','shēntǐ','shenti','身体',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Tomber malade','Tomber malade','To become ill','shēngbìng','shengbing','生病',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Fache','Fache','Angry','shēngqì','shengqi','生气',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Fete, jour de naissance','Fete, jour de naissance','Birthday','shēngrì','shengri','生日',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Voix','Voix','Voice','shēngyīn','shengyin','声音',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Temps, l''heure','Temps, l''heure','Time (of day)','shíjiān','shijian','时间',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('???','???','???','shǐ','shi','使',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Le monde, la terre','Le monde, la terre','World, earth','shìjiè','shijie','世界',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Affaire, incident','Affaire, incident','Buisness, incident','shìqing','shiqing','事情',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Montre','Montre','Watch','shǒubiǎo','shoubiao','手表',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Cellulaire','Cellulaire','Cellular phone','shǒujī','shouji','手机',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('???','???','???','shòu','shou','瘦',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Comfortable','Comfortable','Comfortable','shūfu','shufu','舒服',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Oncle','Oncle','Uncle','shūshu','shushu','叔叔',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Arbre','Arbre','Tree','shù','shu','树',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Mathematiques','Mathematiques','Math','shùxué','shuxue','数学',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Se brosser les dents','Se brosser les dents','Brush teeth','shuāyá','shuaya',' 刷牙',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Paire','Paire','Pair','shuāng','shuang','双',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Niveau','Niveau','Level','shuǐpíng','shuiping','水平',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Conducteur, chauffeur','Conducteur, chauffeur','Driver','sījī','siji','司机',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Livrer (commande)','Livrer (commande)','Deliver (order)','sòng','song','送',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Meme si','Meme si','Even if','suīrán','suiran','虽然',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Donc','Donc','Therefore','suǒyǐ','suoyi','所以',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Ca','Ca','It (thing)','tā','ta','它',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Soleil','Soleil','Sun, sunshine','tàiyáng','taiyang','太阳',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Sucre','Sucre','Sugar','táng','tang','糖',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Inhabituel','Inhabituel','Unsual','tèbié','tebie','特别',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Douleur','Douleur','Pain','téng','teng','疼',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Jouer au football','Jouer au football','Play football','tīzúqiú','tizuqiu',' 踢足球',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Sujet','Sujet','Subject','tí','ti','题',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Ameliorer','Ameliorer','Enhance','tígāo','tigao','提高',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Education physique','Education physique','Physical education','tǐyù','tiyu','体育',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Sucree','Sucree','Sweet','tián','tian','甜',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Bande','Bande','Strip','tiáo','tiao','条',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Danser','Danser','To dance','tiàowǔ','tiaowu','跳舞',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Collegue (de travail)','Collegue (de travail)','Workmate','tóngshì','tongshi','同事',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Etre d''accord','Etre d''accord','To agree','tóngyì','tongyi','同意',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Cheveux','Cheveux','Hair','tóufa','toufa','头发',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Soudainement','Soudainement','Suddenly','tūrán','turan','突然',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Bibliotheque','Bibliotheque','Library','túshūguǎn','tushuguan','图书馆',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Patte, jambe','Patte, jambe','Leg','tuǐ','tui','腿',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Dehors, externe','Dehors, externe','Outside, external','wài','wai','外',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Completer, entier','Completer, entier','Complete, whole','wán','wan','完',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Accomplir','Accomplir','Accomplish','wánchéng','wancheng','完成',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Blaguer','Blaguer','To joke','wán','wan','玩',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Bol','Bol','Bowl','wǎn','wan','碗',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Soiree','Soiree','Evening','wǎnshang','wanshang','晚上',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Dix milles','Dix milles','Ten thousand','wàn','wan','万',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Oublier','Oublier','Forget','wàngjì','wangji','忘记',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Pour','Pour','For','wèi','wei','为',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Afin de (pour)','Afin de (pour)','In order to','wèile','weile','为了',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Pourquoi','Pourquoi','Why','wèishénme','weishenme','为什么',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Endroit, lieu','Endroit, lieu','Place, location','wèi','wei','位',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Culture','Culture','Culture','wénhuà','wenhua','文化',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Demander','Demander','To ask','wèn','wen','问',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Question','Question','Question','wèntí','wenti','问题',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Ouest','Ouest','West','xī','xi','西',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Melon','Melon','Watermelon','xīguā','xigua','西瓜',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Espoir','Espoir','Hope','xīwàng','xiwang','希望',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Etre habitue','Etre habitue','To be used to','xíguàn','xiguan','习惯',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Laver','Laver','To wash','xǐ','xi','洗',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Toilettes','Toilettes','Bathroom','xǐshǒujiān','xishoujian','洗手间',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Se laver','Se laver','To wash oneself','xǐzǎo','xizao','洗澡',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Pleuvoir','Pleuvoir','To rain','xiàyǔ','xiayu','下雨',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('L''ete','L''ete','Summer','xià','xia','夏',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Premier, en avance','Premier, en avance','First, in advance','xiān','xian','先',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Banane','Banane','Banana','xiāngjiāo','xiangjiao','香蕉',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Identique, egal','Identique, egal','Identical, equal','xiāngtóng','xiangtong','相同',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Croire','Croire','To believe','xiāngxìn','xiangxin','相信',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Vers?','Vers?','Toward?','xiàng','xiang','向',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Comme, tel que','Comme, tel que','Like, as','xiàng','xiang','像',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Une heure','Une heure','An hour','xiǎoshí','xiaoshi','小时',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Faire attention','Faire attention','To be careful','xiǎoxīn','xiaoxin','小心',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Rire','Rire','Laugh','xiào','xiao','笑',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Directeur (d''ecole)','Directeur (d''ecole)','Headmaster, schoolmaster','xiàozhǎng','xiaozhang','校长',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Souliers','Souliers','Shoes','xié','xie','鞋',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Nouveau','Nouveau','New','xīn','xin','新',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Nouvelles','Nouvelles','News','xīnwén','xinwen','新闻',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Frais, bon','Frais, bon','Fresh, good','xīnxiān','xinxian','新鲜',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Faire confiance?','Faire confiance?','Trust?','xìn','xin','信',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Coffre, valise','Coffre, valise','Trunk (car)','xínglixiāng','xinglixiang','行李箱',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Nom de famille','Nom de famille','Last name','xìng','xing','姓',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Interet, gout','Interet, gout','Interest, taste','xìngqù','xingqu','兴趣',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Panda','Panda','Panda','xióngmāo','xiongmao','熊猫',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Se reposer','Se reposer','To rest','xiūxi','xiuxi','休息',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Besoin','Besoin','A need','xūyào','xuyao','需要',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Choisir','Choisir','Choose','xuǎnzé','xuanze','选择',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Neige','Neige','Snow','xuě','xue','雪',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Couleur','Couleur','Color','yánsè','yanse','颜色',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Lunettes','Lunettes','(Eye)glasses','yǎnjìng','yanjing','眼镜',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Oeil','Oeil','Eye','yǎnjing','yanjing','眼睛',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Mouton','Mouton','Lamb','yángròu','yangrou','羊肉',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Requis, reclamation','Requis, reclamation','Requirement, claim','yāoqiú','yaoqiu','要求',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Medicaments','Medicaments','Medication','yào','yao','药',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Vouloir','Vouloir','want','yào','yao','要',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Grand-pere','Grand-pere','Grandfather','yéye','yeye','爷爷',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Aussi','Aussi','Also','yě','ye','也',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Regilier, etablit','Regilier, etablit','Regular, established','yídìng','yiding','一定',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('En tout','En tout','Altogether','yígòng','yigong','一共',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Bientot','Bientot','Soon','yíhuìr','yihuir','一会儿',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Pareil, identique','Pareil, identique','Identical','yíyàng','yiyang','一样',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Apres, plus tard','Apres, plus tard','After, later','yǐhòu','yihou','以后',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Avant','Avant','Before','yǐqián','yiqian','以前',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Presumer','Presumer','Take for granted that','yǐwéi','yiwei','以为',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Deja','Deja','Already','yǐjīng','yijing','已经',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Generalement','Generalement','Generally','yìbān','yiban','一般',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Un cote','Un cote','A side','yìbiān','yibian','一边',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Au meme endroit','Au meme endroit','In the same place','yìqǐ','yiqi','一起',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Tout droit','Tout droit','Straight (ahead)','yìzhí','yizhi','一直',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Sens, signification','Sens, signification','Meaning','yìsi','yisi','意思',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Lune','Lune','Moon','yīn','yin','阴',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Parce que','Parce que','Because','yīnwèi','yinwei','因为',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Musique','Musique','Music','yīnyuè','yinyue','音乐',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Banque','Banque','Bank','yínháng','yinhang','银行',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Devrait, Doit','Devrait, Doit','Should, must','yīnggāi','yinggai','应该',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Impression, Influance','Impression, Influance','Impression, Influence','yǐngxiǎng','yingxiang','影响',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Utiliser','Utiliser','Use','yòng','yong','用',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Jeux','Jeux','Game','yóuxì','youxi','游戏',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Nager','Nager','swim','yóuyǒng','youyong','游泳',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Fameux, celebre','Fameux, celebre','Famous','yǒumíng','youming','有名',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Encore','Encore','Again','yòu','you','又',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('A droite, cote droit','A droite, cote droit','Right side','yòubian','youbian','右边',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Poisson','Poisson','Fish','yú','yu','鱼',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Rencontrer','Rencontrer','Encounter','yùdào','yudao','遇到',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Premier, plus haut','Premier, plus haut','First, highest','yuán','yuan','元',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Loin','Loin','Far','yuǎn','yuan','远',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Vouloir, etre pret','Vouloir, etre pret','To be willing, to be ready','yuànyì','yuanyi','愿意',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Lune','Lune','Moon','yuèliang','yueliang','月亮',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Sauter par dessus','Sauter par dessus','Jump over','yuè','yue','越',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Nuage','Nuage','Cloud','yún','yun','云',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Mouvement, voyager','Mouvement, voyager','Movement, travel','yùndòng','yundong','运动',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Encore, une fois de plus','Encore, une fois de plus','Again, once more','zài','zai','再',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Matin','Matin','Morning','zǎoshang','zaoshang','早上',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('???','???','???','zhàn','zhan','站',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Etendre','Etendre','To spread','zhāng','zhang','张',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('???','???','???','zhǎng','zhang','长',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Mari, epoux, conjoint','Mari, epoux, conjoint','Husband','zhàngfu','zhangfu','丈夫',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('S''inquieter','S''inquieter','To worry','zháojí','zhaoji','着急',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Chercher','Chercher','Look for','zhǎo','zhao','找',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('???','???','???','zhàogù','zhaogu','照顾',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Image, photo','Image, photo','Picture','zhàopiàn','zhaopian','照片',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Camera','Camera','Camera','zhàoxiàngjī','zhaoxiangji','照相机',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('???','???','???','zhe','zhe','着',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Reel, vrai','Reel, vrai','Real, true','zhēn','zhen','真',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('En train de','En train de','In the process of','zhèngzài','zhengzai','正在',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Savoir','Savoir','To know','zhīdào','zhidao','知道',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Seulement','Seulement','Only','zhǐ','zhi','只',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Entre, au milieu','Entre, au milieu','Between, in the middle','zhōngjiān','zhongjian','中间',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Finalement','Finalement','Finally','zhōngyú','zhongyu','终于',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Planter','Planter','To plant','zhǒng','zhong','种',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Important, vital','Important, vital','Important, vital','zhòngyào','zhongyao','重要',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Fin de semaine','Fin de semaine','Weekend','zhōumò','zhoumo','周末',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Principal','Principal','Main','zhǔyào','zhuyao','主要',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Exprimer ses voeux','Exprimer ses voeux','Express good wishes','zhù','zhu','祝',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Porter attention','Porter attention','Pay attention','zhùyì','zhuyi','注意',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Preparer?','Preparer?','Prepare','zhǔnbèi','zhunbei','准备',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Dictionary','Dictionary','Dictionnaire','zìdiǎn','zidian','字典',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Se','Se','Oneself, himself','zìjǐ','ziji','自己',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Velo, bicycle','Velo, bicycle','Bike, bicycle','zìxíngchē','zixingche','自行车',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Toujours','Toujours','Always','zǒngshì','zongshi','总是',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Y aller','Y aller','To go','zǒu','zou','走',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Le plus','Le plus','(The) most','zuì','zui','最',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Recemment','Recemment','Recently','zuìjìn','zuijin','最近',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('A gauche, cote gauche','A gauche, cote gauche','Left, left side','zuǒbian','zuobian','左边',2,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Devoirs','Devoirs','Homework','zuòyè','zuoye','作业',3,0,0,0);
INSERT INTO WordItems (`FR`,`AFR`,`EN`,`PY`,`APY`,`CN`,`Lvl`,`HintCN`,`HintPY`,`HintFR`) VALUES('Agir sur','Agir sur','Act on','zuòyòng','zuoyong','作用',3,0,0,0);
